config/routes.rb
SystemStatus::Application.routes.draw do
  resources :systems

end

app/models/system.rb
class System < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  # GET /systems
  # GET /systems.xml
  def index
    @systems = System.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @systems }
      format.json  { render :json => @systems }
    end
  end

  # GET /systems/1
  # GET /systems/1.xml
  def show
    @system = System.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @system }
      format.json  { render :json => @system }
    end
  end

  # GET /systems/new
  # GET /systems/new.xml
  def new
    @system = System.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @system }
    end
  end

  # GET /systems/1/edit
  def edit
    @system = System.find(params[:id])
  end

  # POST /systems
  # POST /systems.xml
  def create
    @system = System.new(params[:system])

    respond_to do |format|
      if @system.save
        format.html { redirect_to(@system, :notice => 'System was successfully created.') }
        format.xml  { render :xml => @system, :status => :created, :location => @system }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /systems/1
  # PUT /systems/1.xml
  def update
    @system = System.find(params[:id])

    respond_to do |format|
      if @system.update_attributes(params[:system])
        format.html { redirect_to(@system, :notice => 'System was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @system.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.xml
  def destroy
    @system = System.find(params[:id])
    @system.destroy

    respond_to do |format|
      format.html { redirect_to(systems_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
  def system_status_icon(system)
    "http://andstone/server_status/images/#{system.status.downcase}.gif"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>System Status</title>
  <link rel="stylesheet" type="text/css" href="http://andstone/server_status/status.css" />
  <script type="text/Javascript" src="http://andstone/server_status/jquery.min.js">
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</script>
</head>

<body>
  <!-- Begin Wrapper -->

  <div id="wrapper">
    <!-- Begin Content -->

    <div id="content">

<%= yield %>

    </div><!-- End Content -->
  </div><!-- End Wrapper -->
</body>
</html>

app/views/systems/_form.html.erb
<style>
	#content { padding: 1em; }
</style>

<%= form_for(@system) do |f| %>
  <% if @system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% @system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
	<%= f.select :status, ["OK", "WARN", "DOWN"].map {|x| [x, x] } %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/systems/edit.html.erb
<h1>Editing system</h1>

<%= render 'form' %>

<%= link_to 'Show', @system %> |
<%= link_to 'Back', systems_path %> |
<%= link_to 'Destroy', @system, :confirm => 'Are you sure you want to delete this system?  There is no way to get it back!', :method => :delete %>

app/views/systems/index.html.erb
      <div class="titlerow">
        <h1>Internal Systems</h1>

        <h3 class="clear statusheader">Current Status</h3>

        <h3 class="notesheader">Notes</h3>

        <h3 class="rssheader">RSS</h3>
      </div>

<% @systems.each do |system| %>
      <div class="row">
        <div class="selectors hidden" id="selector0">
			<%= system.status %>
		</div><img class="states status0" src="<%= system_status_icon(system) %>" />

        <div class="names">
			<%= system.name %>
        </div>

        <div class="notes">
			<%= system.note %>
			&mdash; <%= time_ago_in_words(system.updated_at) %>
        </div>

        <div class="rss">
          <a href="0.rss"><img src="http://andstone/server_status/images/feed.png" /></a>
        </div>

        <div class="editnotes">
			<%= link_to 'Edit', edit_system_path(system) %>
        </div>
      </div>
<% end %>

      <div id="controls">
		<%= link_to 'New System', new_system_path %>
      </div>

app/views/systems/new.html.erb
<h1>New system</h1>

<%= render 'form' %>

<%= link_to 'Back', systems_path %>

app/views/systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @system.name %>
</p>

<p>
  <b>Status:</b>
  <%= @system.status %>
</p>

<p>
  <b>Note:</b>
  <%= @system.note %>
</p>


<%= link_to 'Edit', edit_system_path(@system) %> |
<%= link_to 'Back', systems_path %>